# Generated by Django 5.2.3 on 2025-06-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Plot', 'Plot'), ('Commercial', 'Commercial')], max_length=50)),
                ('size_sqft', models.CharField(max_length=100)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('furnishing_status', models.CharField(blank=True, choices=[('Furnished', 'Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Unfurnished', 'Unfurnished')], max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('construction_status', models.CharField(choices=[('Ready to Move', 'Ready to Move'), ('Under Construction', 'Under Construction')], max_length=50)),
                ('age_of_property', models.CharField(choices=[('New', 'New'), ('Less than 5 years', 'Less than 5 years'), ('5-10 years', '5-10 years'), ('10+ years', '10+ years')], max_length=50)),
                ('floor_number', models.IntegerField()),
                ('total_floors', models.IntegerField()),
                ('parking', models.BooleanField()),
                ('images', models.FileField(blank=True, null=True, upload_to='property_images/')),
                ('floor_plan', models.FileField(blank=True, null=True, upload_to='property_floor_plans/')),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_contact', models.CharField(max_length=15)),
                ('seller_email', models.EmailField(max_length=254)),
                ('seller_type', models.CharField(choices=[('Owner', 'Owner'), ('Agent', 'Agent'), ('Builder', 'Builder')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
