# Generated by Django 5.2.3 on 2025-06-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostProperty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylisting',
            name='floor_plan',
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
